site_name: godot-engine.easy-charts
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Theming: theming.md
  - Advanced: advanced-topics.md

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
